/**
 * GenericSigningBrandingPanel — Collapsible branding customization panel
 * for the Super Admin Generic PDF Signing wizard.
 *
 * Allows: logo upload, firm footer fields, preset save/load, live preview.
 * Audit truthfulness: always states "Generated by Andromeda Legal" regardless of branding toggle.
 */

import { useState, useRef, useEffect, useCallback } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import {
  Image as ImageIcon, Upload, Save, Loader2, ChevronDown, ChevronRight,
  Palette, Eye, Lock, AlertTriangle, Bookmark, Trash2, X
} from "lucide-react";
import { toast } from "sonner";

// ── Types ──

export interface BrandingConfig {
  logoPath: string | null;
  logoBase64: string | null;
  firmName: string;
  firmAddress: string;
  firmPhone: string;
  firmEmail: string;
  firmWebsite: string;
  firmTagline: string;
  showAndromedaBranding: boolean;
  presetId: string | null;
}

export const DEFAULT_BRANDING: BrandingConfig = {
  logoPath: null,
  logoBase64: null,
  firmName: "",
  firmAddress: "",
  firmPhone: "",
  firmEmail: "",
  firmWebsite: "",
  firmTagline: "",
  showAndromedaBranding: true,
  presetId: null,
};

interface Props {
  branding: BrandingConfig;
  onChange: (branding: BrandingConfig) => void;
  userId: string;
}

export function GenericSigningBrandingPanel({ branding, onChange, userId }: Props) {
  const queryClient = useQueryClient();
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [open, setOpen] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [savingPreset, setSavingPreset] = useState(false);
  const [presetName, setPresetName] = useState("");
  const [showSavePreset, setShowSavePreset] = useState(false);
  const [logoPreviewUrl, setLogoPreviewUrl] = useState<string | null>(null);

  // ── Load presets ──
  const { data: presets } = useQuery({
    queryKey: ["generic-signing-branding-presets"],
    queryFn: async () => {
      const { data } = await (supabase as any)
        .from("generic_signing_branding_presets")
        .select("*")
        .order("is_default", { ascending: false })
        .order("name");
      return data || [];
    },
  });

  // ── Compute logo preview URL ──
  useEffect(() => {
    if (branding.logoPath) {
      setLogoPreviewUrl(
        `${import.meta.env.VITE_SUPABASE_URL}/storage/v1/object/public/branding/${branding.logoPath}`
      );
    } else {
      setLogoPreviewUrl(null);
    }
  }, [branding.logoPath]);

  // ── Logo upload ──
  const handleLogoUpload = useCallback(async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    if (!["image/png", "image/svg+xml", "image/jpeg"].includes(file.type)) {
      toast.error("Solo se aceptan PNG, SVG o JPG"); return;
    }
    if (file.size > 2 * 1024 * 1024) {
      toast.error("Máximo 2MB"); return;
    }

    setUploading(true);
    try {
      const ext = file.type === "image/svg+xml" ? "svg" : file.type === "image/png" ? "png" : "jpg";
      const path = `generic-signing/${userId}/logo-${Date.now()}.${ext}`;

      const { error } = await supabase.storage
        .from("branding")
        .upload(path, file, { upsert: true, contentType: file.type });
      if (error) throw error;

      // Also create base64 for PDF embedding
      const reader = new FileReader();
      reader.onload = () => {
        const base64 = reader.result as string;
        // Warn if base64 is too large (> 500KB encoded)
        if (base64.length > 500_000) {
          toast.warning("Logo grande: podría afectar el rendimiento del PDF. Se recomienda < 500KB.");
        }
        onChange({ ...branding, logoPath: path, logoBase64: base64 });
      };
      reader.readAsDataURL(file);

      toast.success("Logo subido");
    } catch (err: any) {
      toast.error(err.message || "Error al subir logo");
    } finally {
      setUploading(false);
      if (fileInputRef.current) fileInputRef.current.value = "";
    }
  }, [branding, onChange, userId]);

  // ── Remove logo ──
  const handleRemoveLogo = useCallback(() => {
    onChange({ ...branding, logoPath: null, logoBase64: null });
  }, [branding, onChange]);

  // ── Field updaters ──
  const updateField = useCallback((field: keyof BrandingConfig, value: string | boolean) => {
    onChange({ ...branding, [field]: value });
  }, [branding, onChange]);

  // ── Load preset ──
  const handleLoadPreset = useCallback((presetId: string) => {
    const preset = presets?.find((p: any) => p.id === presetId);
    if (!preset) return;

    onChange({
      logoPath: preset.logo_path,
      logoBase64: null, // Will be re-fetched from storage URL
      firmName: preset.firm_name || "",
      firmAddress: preset.firm_address || "",
      firmPhone: preset.firm_phone || "",
      firmEmail: preset.firm_email || "",
      firmWebsite: preset.firm_website || "",
      firmTagline: preset.firm_tagline || "",
      showAndromedaBranding: preset.show_andromeda_branding,
      presetId: preset.id,
    });

    // If preset has a logo, fetch its base64
    if (preset.logo_path) {
      const url = `${import.meta.env.VITE_SUPABASE_URL}/storage/v1/object/public/branding/${preset.logo_path}`;
      fetch(url)
        .then(r => r.blob())
        .then(blob => {
          const reader = new FileReader();
          reader.onload = () => {
            onChange({
              logoPath: preset.logo_path,
              logoBase64: reader.result as string,
              firmName: preset.firm_name || "",
              firmAddress: preset.firm_address || "",
              firmPhone: preset.firm_phone || "",
              firmEmail: preset.firm_email || "",
              firmWebsite: preset.firm_website || "",
              firmTagline: preset.firm_tagline || "",
              showAndromedaBranding: preset.show_andromeda_branding,
              presetId: preset.id,
            });
          };
          reader.readAsDataURL(blob);
        })
        .catch(() => {});
    }

    toast.success(`Preset "${preset.name}" cargado`);
  }, [presets, onChange]);

  // ── Save preset ──
  const handleSavePreset = useCallback(async () => {
    if (!presetName.trim()) { toast.error("Ingrese un nombre"); return; }
    setSavingPreset(true);
    try {
      const { error } = await (supabase as any)
        .from("generic_signing_branding_presets")
        .insert({
          created_by: userId,
          name: presetName.trim(),
          logo_path: branding.logoPath,
          firm_name: branding.firmName || null,
          firm_address: branding.firmAddress || null,
          firm_phone: branding.firmPhone || null,
          firm_email: branding.firmEmail || null,
          firm_website: branding.firmWebsite || null,
          firm_tagline: branding.firmTagline || null,
          show_andromeda_branding: branding.showAndromedaBranding,
        });
      if (error) throw error;
      queryClient.invalidateQueries({ queryKey: ["generic-signing-branding-presets"] });
      setShowSavePreset(false);
      setPresetName("");
      toast.success("Preset guardado");
    } catch (err: any) {
      toast.error(err.message || "Error al guardar preset");
    } finally {
      setSavingPreset(false);
    }
  }, [userId, branding, presetName, queryClient]);

  // ── Delete preset ──
  const handleDeletePreset = useCallback(async (id: string) => {
    try {
      await (supabase as any).from("generic_signing_branding_presets").delete().eq("id", id);
      queryClient.invalidateQueries({ queryKey: ["generic-signing-branding-presets"] });
      toast.success("Preset eliminado");
    } catch { toast.error("Error al eliminar"); }
  }, [queryClient]);

  const hasAnyBranding = !!(branding.logoPath || branding.firmName || branding.firmAddress || branding.firmPhone || branding.firmEmail);

  return (
    <Collapsible open={open} onOpenChange={setOpen}>
      <CollapsibleTrigger asChild>
        <button className="w-full flex items-center justify-between p-3 rounded-lg bg-white/5 border border-white/10 hover:bg-white/8 transition-colors text-left">
          <div className="flex items-center gap-2">
            <Palette className="h-4 w-4 text-cyan-400" />
            <span className="text-sm font-medium text-white">Personalización de Marca</span>
            {hasAnyBranding && (
              <span className="text-[10px] bg-cyan-500/20 text-cyan-400 px-1.5 py-0.5 rounded">Personalizado</span>
            )}
          </div>
          {open ? <ChevronDown className="h-4 w-4 text-white/40" /> : <ChevronRight className="h-4 w-4 text-white/40" />}
        </button>
      </CollapsibleTrigger>

      <CollapsibleContent>
        <div className="mt-3 space-y-4">
          {/* Preset selector */}
          {presets && presets.length > 0 && (
            <div className="space-y-1">
              <Label className="text-white/60 text-xs">Cargar preset guardado</Label>
              <Select onValueChange={handleLoadPreset} value={branding.presetId || ""}>
                <SelectTrigger className="bg-white/5 border-white/15 text-white text-sm">
                  <SelectValue placeholder="Seleccionar preset..." />
                </SelectTrigger>
                <SelectContent>
                  {presets.map((p: any) => (
                    <SelectItem key={p.id} value={p.id}>
                      {p.name} {p.is_default ? "⭐" : ""}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          )}

          {/* Logo upload */}
          <div className="space-y-2">
            <Label className="text-white/60 text-xs">Logo de la firma</Label>
            <div className="flex items-center gap-3">
              <div className="w-32 h-16 rounded border border-white/10 bg-white/5 flex items-center justify-center overflow-hidden">
                {logoPreviewUrl ? (
                  <img src={logoPreviewUrl} alt="Logo" className="max-h-full max-w-full object-contain" />
                ) : (
                  <span className="text-[10px] text-white/30">Sin logo</span>
                )}
              </div>
              <div className="flex flex-col gap-1">
                <input ref={fileInputRef} type="file" accept=".png,.svg,.jpg,.jpeg" className="hidden" onChange={handleLogoUpload} />
                <Button variant="outline" size="sm" onClick={() => fileInputRef.current?.click()} disabled={uploading} className="border-white/15 text-white/60 hover:text-white text-xs h-7">
                  {uploading ? <Loader2 className="h-3 w-3 animate-spin mr-1" /> : <Upload className="h-3 w-3 mr-1" />}
                  Subir logo
                </Button>
                {branding.logoPath && (
                  <Button variant="ghost" size="sm" onClick={handleRemoveLogo} className="text-white/40 hover:text-red-400 text-xs h-7">
                    <X className="h-3 w-3 mr-1" /> Quitar
                  </Button>
                )}
              </div>
            </div>
            <p className="text-[10px] text-white/30">PNG/SVG/JPG · Máx 2MB · Fondo transparente recomendado</p>
          </div>

          {/* Firm identity fields */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div className="space-y-1 sm:col-span-2">
              <Label className="text-white/60 text-xs">Nombre de la firma</Label>
              <Input value={branding.firmName} onChange={e => updateField("firmName", e.target.value)} placeholder="García & Asociados" className="bg-white/5 border-white/15 text-white placeholder:text-white/30 h-9 text-sm" />
            </div>
            <div className="space-y-1 sm:col-span-2">
              <Label className="text-white/60 text-xs">Dirección</Label>
              <Input value={branding.firmAddress} onChange={e => updateField("firmAddress", e.target.value)} placeholder="Cra 7 #71-21 Of. 801, Bogotá" className="bg-white/5 border-white/15 text-white placeholder:text-white/30 h-9 text-sm" />
            </div>
            <div className="space-y-1">
              <Label className="text-white/60 text-xs">Teléfono</Label>
              <Input value={branding.firmPhone} onChange={e => updateField("firmPhone", e.target.value)} placeholder="+57 601 234 5678" className="bg-white/5 border-white/15 text-white placeholder:text-white/30 h-9 text-sm" />
            </div>
            <div className="space-y-1">
              <Label className="text-white/60 text-xs">Email de la firma</Label>
              <Input value={branding.firmEmail} onChange={e => updateField("firmEmail", e.target.value)} placeholder="contacto@firma.com" className="bg-white/5 border-white/15 text-white placeholder:text-white/30 h-9 text-sm" />
            </div>
            <div className="space-y-1">
              <Label className="text-white/60 text-xs">Sitio web (opcional)</Label>
              <Input value={branding.firmWebsite} onChange={e => updateField("firmWebsite", e.target.value)} placeholder="www.firma.com" className="bg-white/5 border-white/15 text-white placeholder:text-white/30 h-9 text-sm" />
            </div>
            <div className="space-y-1">
              <Label className="text-white/60 text-xs">Tagline (opcional)</Label>
              <Input value={branding.firmTagline} onChange={e => updateField("firmTagline", e.target.value)} placeholder="Derecho Corporativo" className="bg-white/5 border-white/15 text-white placeholder:text-white/30 h-9 text-sm" />
            </div>
          </div>

          {/* Show Andromeda branding toggle */}
          <div className="flex items-center justify-between p-3 rounded-lg bg-white/5 border border-white/10">
            <div className="space-y-0.5">
              <Label className="text-white/80 text-sm">Mostrar marca Andromeda en documento</Label>
              <p className="text-[10px] text-white/40">El certificado de auditoría siempre incluirá "Generado por Andromeda Legal"</p>
            </div>
            <Switch
              checked={branding.showAndromedaBranding}
              onCheckedChange={(v) => updateField("showAndromedaBranding", v)}
            />
          </div>

          {/* Audit truthfulness notice */}
          <div className="flex items-start gap-2 p-2.5 rounded-lg bg-amber-500/10 border border-amber-500/20">
            <AlertTriangle className="h-3.5 w-3.5 text-amber-400 shrink-0 mt-0.5" />
            <p className="text-[10px] text-amber-200/80">
              <strong>Invariante de auditoría:</strong> Independientemente de la marca visible, el certificado de auditoría siempre indicará: "Remitente del sistema: info@andromeda.legal" y "Generado por Andromeda Legal".
            </p>
          </div>

          {/* Save as preset */}
          <div className="flex items-center gap-2">
            {!showSavePreset ? (
              <Button variant="outline" size="sm" onClick={() => setShowSavePreset(true)} className="border-white/15 text-white/60 hover:text-white text-xs h-7">
                <Bookmark className="h-3 w-3 mr-1" /> Guardar como preset
              </Button>
            ) : (
              <div className="flex items-center gap-2 flex-1">
                <Input value={presetName} onChange={e => setPresetName(e.target.value)} placeholder="Nombre del preset" className="bg-white/5 border-white/15 text-white placeholder:text-white/30 h-8 text-xs flex-1" />
                <Button size="sm" onClick={handleSavePreset} disabled={savingPreset} className="bg-cyan-600 hover:bg-cyan-700 text-xs h-8">
                  {savingPreset ? <Loader2 className="h-3 w-3 animate-spin" /> : <Save className="h-3 w-3 mr-1" />}
                  Guardar
                </Button>
                <Button variant="ghost" size="sm" onClick={() => { setShowSavePreset(false); setPresetName(""); }} className="text-white/40 h-8">
                  <X className="h-3 w-3" />
                </Button>
              </div>
            )}
          </div>

          {/* Live branding preview */}
          <div className="space-y-2">
            <Label className="text-white/60 text-xs flex items-center gap-1">
              <Eye className="h-3 w-3" /> Vista previa de marca
            </Label>
            <div className="rounded-lg border border-white/10 overflow-hidden">
              {/* Signature page preview */}
              <div className="bg-white p-4 space-y-3">
                {/* Header */}
                <div className="text-center space-y-1 border-b border-gray-200 pb-3">
                  {logoPreviewUrl ? (
                    <img src={logoPreviewUrl} alt="Logo" className="max-h-[40px] mx-auto object-contain" />
                  ) : branding.showAndromedaBranding ? (
                    <p className="font-bold text-sm tracking-tight" style={{ color: "#1a1a2e" }}>ANDROMEDA LEGAL</p>
                  ) : null}
                  {branding.firmName && (
                    <p className="text-xs font-medium" style={{ color: "#333" }}>{branding.firmName}</p>
                  )}
                  {branding.firmTagline && (
                    <p className="text-[9px]" style={{ color: "#888" }}>{branding.firmTagline}</p>
                  )}
                </div>

                {/* Body placeholder */}
                <div className="text-center py-3">
                  <p className="text-[10px]" style={{ color: "#999" }}>[Bloque de firmas del documento]</p>
                </div>

                {/* Footer */}
                <div className="border-t border-gray-200 pt-2 text-center space-y-0.5">
                  {branding.firmName && (
                    <p className="text-[9px] font-medium" style={{ color: "#555" }}>{branding.firmName}</p>
                  )}
                  {(branding.firmAddress || branding.firmPhone || branding.firmEmail) && (
                    <p className="text-[8px]" style={{ color: "#888" }}>
                      {[branding.firmAddress, branding.firmPhone, branding.firmEmail].filter(Boolean).join(" · ")}
                    </p>
                  )}
                  {branding.firmWebsite && (
                    <p className="text-[8px]" style={{ color: "#888" }}>{branding.firmWebsite}</p>
                  )}
                  {branding.showAndromedaBranding && (
                    <div className="flex items-center justify-center gap-1 mt-1">
                      <Lock className="h-2 w-2" style={{ color: "#aaa" }} />
                      <span className="text-[7px]" style={{ color: "#aaa" }}>Documento generado por Andromeda Legal · info@andromeda.legal</span>
                    </div>
                  )}
                </div>
              </div>
            </div>
            <p className="text-[10px] text-white/30">
              Esta marca se aplicará a las páginas de firma y certificado de auditoría. El PDF original no se modifica.
            </p>
          </div>
        </div>
      </CollapsibleContent>
    </Collapsible>
  );
}
