// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-work-items.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/shared.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";

// src/lib/search/normalized-search.ts
var MIN_PARTIAL_DIGITS = 4;
function digitsOf(value) {
  return String(value ?? "").replace(/\D/g, "");
}
function radicadoQueryVariants(query) {
  const digits = digitsOf(query);
  if (digits.length >= 23) {
    const d23 = digits.slice(0, 23);
    return { digits, canonical23: d23, base21: d23.slice(0, 21), partial: false };
  }
  if (digits.length === 22) {
    const padded = `0${digits}`;
    return { digits, canonical23: padded, base21: padded.slice(0, 21), partial: false };
  }
  if (digits.length === 21) {
    return { digits, canonical23: `${digits}00`, base21: digits, partial: false };
  }
  return {
    digits,
    canonical23: null,
    base21: null,
    partial: digits.length >= MIN_PARTIAL_DIGITS
  };
}

// src/lib/mcp/shared.ts
function sbForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var WORKFLOW_TOKENS = /* @__PURE__ */ new Set([
  "CGP",
  "CPACA",
  "LABORAL",
  "PENAL_906",
  "PENAL",
  "TUTELA",
  "PETICION",
  "GOV_PROCEDURE",
  "GENERIC"
]);
function collapseParties(raw) {
  const parts = raw.split(/\s*(?:,|;|\||\/| y otros? )\s*/i).map((p) => p.trim()).filter(Boolean);
  if (parts.length <= 2) return parts.join(", ") || raw.trim();
  return `${parts.slice(0, 2).join(", ")} y ${parts.length - 2} m\xE1s`;
}
function workItemTitle(wi, fallback) {
  const raw = wi?.title ? String(wi.title).trim() : "";
  const normalized = raw.toUpperCase().replace(/[\s-]+/g, "_");
  if (raw && !WORKFLOW_TOKENS.has(normalized)) {
    return raw.length > 180 ? `${raw.slice(0, 177)}\u2026` : raw;
  }
  const dte = wi?.demandantes ? collapseParties(String(wi.demandantes)) : "";
  const ddo = wi?.demandados ? collapseParties(String(wi.demandados)) : "";
  const partes = dte && ddo ? `${dte} vs ${ddo}` : dte || ddo;
  if (partes) return partes;
  if (wi?.radicado) return String(wi.radicado);
  return fallback ? String(fallback) : "Asunto sin t\xEDtulo";
}
var MAX_JSON_CHARS = 9e4;
function textResult(text, structuredContent) {
  if (!structuredContent) {
    return { content: [{ type: "text", text }] };
  }
  let json = JSON.stringify(structuredContent, null, 2);
  let truncated = false;
  if (json.length > MAX_JSON_CHARS) {
    json = JSON.stringify(structuredContent);
    if (json.length > MAX_JSON_CHARS) {
      json = json.slice(0, MAX_JSON_CHARS);
      truncated = true;
    }
  }
  const body = truncated ? `${text}

(Respuesta truncada: reduce el par\xE1metro \`limit\` para ver todo.)

\`\`\`json
${json}
\`\`\`` : `${text}

\`\`\`json
${json}
\`\`\``;
  return { content: [{ type: "text", text: body }], structuredContent };
}
function businessDaysBetween(fromISO, toISO, holidays = /* @__PURE__ */ new Set()) {
  const start = /* @__PURE__ */ new Date(`${fromISO}T12:00:00Z`);
  const end = /* @__PURE__ */ new Date(`${toISO}T12:00:00Z`);
  const sign = end < start ? -1 : 1;
  let count = 0;
  const cursor = new Date(sign > 0 ? start : end);
  const stop = sign > 0 ? end : start;
  while (cursor < stop) {
    cursor.setUTCDate(cursor.getUTCDate() + 1);
    const iso = cursor.toISOString().slice(0, 10);
    const dow = cursor.getUTCDay();
    if (dow !== 0 && dow !== 6 && !holidays.has(iso)) count += 1;
  }
  return count * sign;
}
function errorResult(text) {
  return { content: [{ type: "text", text }], isError: true };
}
function requireAuth(ctx) {
  return ctx.isAuthenticated() ? null : "No autenticado. Vuelve a conectar la herramienta con tu cuenta de Andromeda.";
}
function requireWriteScope(ctx) {
  const unauth = requireAuth(ctx);
  if (unauth) return unauth;
  const claims = ctx.getClaims?.() ?? {};
  const raw = claims.scope ?? claims.scopes ?? claims.scp;
  if (raw == null) return null;
  const granted = Array.isArray(raw) ? raw.map(String) : String(raw).split(/[\s,]+/);
  return granted.includes("read_write") ? null : "Esta conexi\xF3n es de solo lectura. Autoriza el permiso `read_write` para escribir en Andromeda.";
}
async function callerOrganizationId(sb, userId) {
  const { data } = await sb.from("organization_memberships").select("organization_id").eq("user_id", userId).limit(1).maybeSingle();
  return data?.organization_id ?? null;
}
function bogotaToday() {
  return (/* @__PURE__ */ new Date()).toLocaleDateString("en-CA", { timeZone: "America/Bogota" });
}
var NOT_PLATFORM_ADMIN = "Esta herramienta est\xE1 restringida a administradores de la plataforma.";
async function requirePlatformAdmin(ctx) {
  const sb = sbForUser(ctx);
  const unauth = requireAuth(ctx);
  if (unauth) return { error: unauth, sb };
  const userId = ctx.getUserId?.();
  if (!userId) return { error: NOT_PLATFORM_ADMIN, sb };
  const { data, error } = await sb.from("platform_admins").select("user_id, role").eq("user_id", userId).maybeSingle();
  if (error || !data) return { error: NOT_PLATFORM_ADMIN, sb };
  return { error: null, sb };
}
var INACTIVE_LIFECYCLE = /* @__PURE__ */ new Set(["DELETED", "ARCHIVED", "CLOSED", "TERMINATED"]);
function instanceSuffix(radicado) {
  const d = digitsOf(String(radicado ?? ""));
  return d.length >= 23 ? Number(d.slice(21, 23)) : 0;
}
async function resolveWorkItem(sb, args, columns = "id, radicado, title, workflow_type, stage, authority_name, client_id") {
  const select = columns.includes("radicado_digits") ? columns : `${columns}, radicado_digits, lifecycle_state, updated_at`;
  if (args.id) {
    const { data, error } = await sb.from("work_items").select(select).is("deleted_at", null).eq("id", args.id).limit(1);
    if (error) return { item: null, error: error.message };
    const item = data?.[0];
    return item ? { item, error: null, note: null } : { item: null, error: "Asunto no encontrado (o no pertenece a tu cuenta)." };
  }
  const raw = (args.radicado ?? "").trim();
  if (!raw) return { item: null, error: "Indica el id o el radicado del asunto." };
  const v = radicadoQueryVariants(raw);
  let rows = [];
  if (v.base21) {
    const { data, error } = await sb.from("work_items").select(select).is("deleted_at", null).like("radicado_digits", `${v.base21}%`).limit(20);
    if (error) return { item: null, error: error.message };
    rows = data ?? [];
  } else if (v.partial) {
    const { data, error } = await sb.from("work_items").select(select).is("deleted_at", null).like("radicado_digits", `%${v.digits}%`).limit(20);
    if (error) return { item: null, error: error.message };
    rows = data ?? [];
  } else {
    const { data, error } = await sb.from("work_items").select(select).is("deleted_at", null).eq("radicado", raw).limit(1);
    if (error) return { item: null, error: error.message };
    rows = data ?? [];
  }
  if (rows.length === 0) {
    return { item: null, error: "Asunto no encontrado (o no pertenece a tu cuenta)." };
  }
  if (rows.length === 1) return { item: rows[0], error: null, note: null };
  const exact = v.canonical23 ? rows.find((r) => digitsOf(String(r.radicado ?? "")) === v.canonical23) : void 0;
  const ranked = [...rows].sort((a, b) => {
    const aInactive = INACTIVE_LIFECYCLE.has(String(a.lifecycle_state ?? "ACTIVE").toUpperCase());
    const bInactive = INACTIVE_LIFECYCLE.has(String(b.lifecycle_state ?? "ACTIVE").toUpperCase());
    if (aInactive !== bInactive) return aInactive ? 1 : -1;
    const bySuffix = instanceSuffix(b.radicado) - instanceSuffix(a.radicado);
    if (bySuffix !== 0) return bySuffix;
    return String(b.updated_at ?? "").localeCompare(String(a.updated_at ?? ""));
  });
  const chosen = exact ?? ranked[0];
  const candidates = rows.map((r) => ({
    id: String(r.id),
    radicado: r.radicado ?? null
  }));
  const note = exact ? `El radicado "${raw}" coincide con ${rows.length} instancias; se us\xF3 la coincidencia exacta ${chosen.radicado}.` : `El radicado "${raw}" coincide con ${rows.length} instancias (${candidates.map((c) => c.radicado ?? c.id).join(", ")}); se resolvi\xF3 a la instancia activa ${chosen.radicado}.`;
  return { item: chosen, error: null, note, candidates };
}

// src/lib/mcp/tools/list-work-items.ts
var list_work_items_default = defineTool({
  name: "list_work_items",
  title: "Listar asuntos (work items)",
  description: "Lists the signed-in user's active legal matters (asuntos) from Andromeda. Supports optional text search and workflow_type filter (CGP, CPACA, LABORAL, PENAL, TUTELA, PETICION).",
  inputSchema: {
    search: z.string().trim().optional().describe("Free-text match on radicado, t\xEDtulo, partes, o autoridad."),
    workflow_type: z.string().trim().optional().describe("Filter by workflow_type, e.g. CGP, CPACA, LABORAL, PENAL, TUTELA, PETICION."),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, workflow_type, limit }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return errorResult(unauth);
    const sb = sbForUser(ctx);
    let q = sb.from("work_items").select("id, radicado, workflow_type, stage, status, authority_name, authority_city, demandantes, demandados, title, last_action_date, last_action_description, updated_at").is("deleted_at", null).order("updated_at", { ascending: false }).limit(limit ?? 25);
    if (workflow_type) q = q.eq("workflow_type", workflow_type.toUpperCase());
    if (search) {
      const s = `%${search}%`;
      q = q.or(`radicado.ilike.${s},title.ilike.${s},authority_name.ilike.${s},demandantes.ilike.${s},demandados.ilike.${s}`);
    }
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return textResult(`Encontrados ${data?.length ?? 0} asuntos.`, { items: data ?? [] });
  }
});

// src/lib/mcp/tools/get-work-item.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_work_item_default = defineTool2({
  name: "get_work_item",
  title: "Detalle de asunto",
  description: "Fetches details for one legal matter (work_item) by id or by radicado, including recent actuaciones and estados.",
  inputSchema: {
    id: z2.string().uuid().optional().describe("work_item UUID."),
    radicado: z2.string().trim().optional().describe(
      "Radicado en cualquier forma: 23 d\xEDgitos, con guiones, con espacios, base de 21 d\xEDgitos, 22 d\xEDgitos sin el cero inicial o base+instancia."
    ),
    verbose: z2.boolean().optional().describe("Si es true devuelve el objeto work_item crudo completo (~150 campos internos). Default false.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, radicado, verbose }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return errorResult(unauth);
    if (!id && !radicado) return errorResult("Indica el id o el radicado del asunto.");
    const sb = sbForUser(ctx);
    const resolved = await resolveWorkItem(sb, { id, radicado }, "*");
    if (resolved.error || !resolved.item) {
      return errorResult(resolved.error ?? "Asunto no encontrado (o no pertenece a tu cuenta).");
    }
    const item = resolved.item;
    const [{ data: acts }, { data: estados }, { data: deadlines }, { data: hearings }] = await Promise.all([
      sb.from("work_item_acts").select("id, act_date, act_type, description, despacho, source, detected_at").eq("work_item_id", item.id).or("is_archived.is.null,is_archived.eq.false").order("act_date", { ascending: false }).limit(20),
      sb.from("work_item_publicaciones").select("id, fecha_fijacion, fecha_desfijacion, tipo_publicacion, title, annotation, despacho, source, pdf_available, detected_at").eq("work_item_id", item.id).or("is_archived.is.null,is_archived.eq.false").order("fecha_fijacion", { ascending: false }).limit(20),
      sb.from("work_item_deadlines").select("id, deadline_type, label, trigger_date, deadline_date, business_days_count, status").eq("work_item_id", item.id).eq("status", "PENDING").order("deadline_date", { ascending: true }).limit(20),
      sb.from("work_item_hearings").select("id, custom_name, status, scheduled_at, modality, location").eq("work_item_id", item.id).order("scheduled_at", { ascending: true }).limit(10)
    ]);
    const resumen = {
      radicado: item.radicado ?? null,
      titulo: item.title ?? null,
      workflow_type: item.workflow_type ?? null,
      stage: item.stage ?? null,
      status: item.status ?? null,
      despacho: item.authority_name ?? null,
      ciudad: item.authority_city ?? null,
      departamento: item.authority_department ?? item.departamento ?? null,
      demandantes: item.demandantes ?? null,
      demandados: item.demandados ?? null,
      client_id: item.client_id ?? null,
      ultima_actuacion: item.last_action_date ?? null,
      ultima_actuacion_descripcion: item.last_action_description ?? null
    };
    const ITEM_FIELDS = [
      "id",
      "radicado",
      "workflow_type",
      "stage",
      "status",
      "lifecycle_state",
      "title",
      "description",
      "authority_name",
      "authority_email",
      "authority_city",
      "authority_department",
      "demandantes",
      "demandados",
      "client_id",
      "cgp_class",
      "cgp_variant",
      "cgp_cuantia",
      "cgp_instancia",
      "ponente",
      "clase_proceso",
      "tipo_proceso",
      "fecha_radicado",
      "total_actuaciones",
      "total_sujetos_procesales",
      "monitoring_enabled",
      "last_successful_sync_at",
      "created_at"
    ];
    const source = item;
    const slimItem = {};
    for (const key of ITEM_FIELDS) {
      if (source[key] !== void 0 && source[key] !== null) slimItem[key] = source[key];
    }
    return textResult(
      `${resolved.note ? `${resolved.note}
` : ""}Asunto ${item.radicado ?? item.id} \u2014 ${item.workflow_type} \u2014 ${item.authority_name ?? "despacho sin registrar"} \u2014 ${acts?.length ?? 0} actuaciones, ${estados?.length ?? 0} estados, ${deadlines?.length ?? 0} t\xE9rminos activos.`,
      {
        resolucion: resolved.note ?? null,
        resumen,
        item: verbose ? item : slimItem,
        recent_acts: acts ?? [],
        recent_estados: estados ?? [],
        terminos_activos: deadlines ?? [],
        audiencias: hearings ?? []
      }
    );
  }
});

// src/lib/mcp/tools/list-recent-estados.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_recent_estados_default = defineTool3({
  name: "list_recent_estados",
  title: "Novedades judiciales recientes",
  description: "Lists the most recent judicial estados / actuaciones detected across the signed-in user's monitored matters, ordered by detected_at desc.",
  inputSchema: {
    days: z3.number().int().min(1).max(30).optional().describe("Ventana en d\xEDas (default 3)."),
    limit: z3.number().int().min(1).max(100).optional().describe("M\xE1ximo filas (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days, limit }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return errorResult(unauth);
    const sb = sbForUser(ctx);
    const since = new Date(Date.now() - (days ?? 3) * 864e5).toISOString();
    const { data, error } = await sb.from("work_item_publicaciones").select("id, work_item_id, title, annotation, tipo_publicacion, despacho, fecha_fijacion, detected_at, source").gte("detected_at", since).or("is_archived.is.null,is_archived.eq.false").order("detected_at", { ascending: false }).limit(limit ?? 25);
    if (error) return errorResult(error.message);
    const ids = [...new Set((data ?? []).map((r) => r.work_item_id))];
    const { data: items } = ids.length ? await sb.from("work_items").select("id, radicado, title, workflow_type").in("id", ids) : { data: [] };
    const byId = new Map(
      (items ?? []).map((i) => [i.id, i])
    );
    const estados = (data ?? []).map((r) => ({
      ...r,
      work_item: byId.get(r.work_item_id) ?? null
    }));
    return textResult(`${estados.length} novedades en los \xFAltimos ${days ?? 3} d\xEDas.`, { estados });
  }
});

// src/lib/mcp/tools/get-user-context.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_user_context_default = defineTool4({
  name: "get_user_context",
  title: "Contexto del abogado",
  description: "Returns the signed-in lawyer's profile (name, firm) and portfolio counters (active matters by workflow type). Call this first so you can address the user correctly without asking.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return errorResult(unauth);
    const sb = sbForUser(ctx);
    const [{ data: profile }, { data: items }] = await Promise.all([
      sb.from("profiles").select("full_name, firm_name, email, timezone").eq("id", ctx.getUserId()).maybeSingle(),
      sb.from("work_items").select("workflow_type").is("deleted_at", null).limit(1e3)
    ]);
    const byType = {};
    for (const row of items ?? []) {
      const key = row.workflow_type ?? "SIN_TIPO";
      byType[key] = (byType[key] ?? 0) + 1;
    }
    const total = items?.length ?? 0;
    const name = profile?.full_name ?? ctx.getUserEmail() ?? "Usuario";
    const firm = profile?.firm_name;
    return textResult(
      `${name}${firm ? ` (${firm})` : ""} \u2014 ${total} asuntos activos: ${Object.entries(byType).map(([k, v]) => `${k}: ${v}`).join(", ") || "ninguno"}.`,
      { profile: profile ?? null, active_work_items: total, by_workflow_type: byType }
    );
  }
});

// src/lib/mcp/tools/list-actuaciones.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_actuaciones_default = defineTool5({
  name: "list_actuaciones",
  title: "Actuaciones de un asunto",
  description: "Lists judicial actuaciones for one matter, newest first. Identify the matter by radicado or work item id. Archived and superseded rows are excluded.",
  inputSchema: {
    radicado: z4.string().trim().optional().describe("Radicado en cualquier forma: 23 d\xEDgitos, con guiones, con espacios, base de 21 d\xEDgitos, 22 d\xEDgitos sin cero inicial o base+instancia."),
    id: z4.string().uuid().optional().describe("UUID del asunto (alternativa al radicado)."),
    date_from: z4.string().optional().describe("Fecha inicial YYYY-MM-DD (sobre act_date)."),
    date_to: z4.string().optional().describe("Fecha final YYYY-MM-DD (sobre act_date)."),
    limit: z4.number().int().min(1).max(200).optional().describe("M\xE1ximo de filas (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ radicado, id, date_from, date_to, limit }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return errorResult(unauth);
    const sb = sbForUser(ctx);
    const resolved = await resolveWorkItem(sb, { id, radicado });
    const item = resolved.item;
    if (resolved.error || !item) return errorResult(resolved.error ?? "Asunto no encontrado.");
    let q = sb.from("work_item_acts").select("id, act_date, act_type, description, despacho, source, detected_at, instancia").eq("work_item_id", item.id).or("is_archived.is.null,is_archived.eq.false").order("act_date", { ascending: false }).limit(limit ?? 50);
    if (date_from) q = q.gte("act_date", date_from);
    if (date_to) q = q.lte("act_date", date_to);
    const { data, error: qErr } = await q;
    if (qErr) return errorResult(qErr.message);
    return textResult(
      `${resolved.note ? `${resolved.note}
` : ""}${data?.length ?? 0} actuaciones para ${item.radicado ?? item.id}.`,
      { resolucion: resolved.note ?? null, work_item: item, actuaciones: data ?? [] }
    );
  }
});

// src/lib/mcp/tools/list-publicaciones.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^3.25.76";
var list_publicaciones_default = defineTool6({
  name: "list_publicaciones",
  title: "Estados electr\xF3nicos de un asunto",
  description: "Lists electronic estados / publicaciones procesales for one matter, newest fijaci\xF3n first. Identify the matter by radicado or work item id.",
  inputSchema: {
    radicado: z5.string().trim().optional().describe("Radicado del asunto."),
    id: z5.string().uuid().optional().describe("UUID del asunto."),
    date_from: z5.string().optional().describe("Fecha inicial YYYY-MM-DD (sobre fecha_fijacion)."),
    date_to: z5.string().optional().describe("Fecha final YYYY-MM-DD (sobre fecha_fijacion)."),
    limit: z5.number().int().min(1).max(200).optional().describe("M\xE1ximo de filas (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ radicado, id, date_from, date_to, limit }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return errorResult(unauth);
    const sb = sbForUser(ctx);
    const { item, error } = await resolveWorkItem(sb, { id, radicado });
    if (error || !item) return errorResult(error ?? "Asunto no encontrado.");
    let q = sb.from("work_item_publicaciones").select("id, fecha_fijacion, fecha_desfijacion, fecha_providencia, tipo_publicacion, title, annotation, despacho, source, pdf_available, detected_at").eq("work_item_id", item.id).or("is_archived.is.null,is_archived.eq.false").order("fecha_fijacion", { ascending: false }).limit(limit ?? 50);
    if (date_from) q = q.gte("fecha_fijacion", date_from);
    if (date_to) q = q.lte("fecha_fijacion", date_to);
    const { data, error: qErr } = await q;
    if (qErr) return errorResult(qErr.message);
    return textResult(
      `${data?.length ?? 0} estados para ${item.radicado ?? item.id}.`,
      { work_item: item, publicaciones: data ?? [] }
    );
  }
});

// src/lib/mcp/tools/get-estados-hoy.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z6 } from "npm:zod@^3.25.76";
var get_estados_hoy_default = defineTool7({
  name: "get_estados_hoy",
  title: "Estados de hoy",
  description: "Lists estados electr\xF3nicos fijados TODAY (America/Bogota) across the whole portfolio. An estado belongs to a day when its fecha_fijacion equals that calendar day in Bogota \u2014 not when it was detected.",
  inputSchema: {
    date: z6.string().optional().describe("D\xEDa YYYY-MM-DD en America/Bogota. Default: hoy."),
    limit: z6.number().int().min(1).max(200).optional().describe("M\xE1ximo de filas (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date, limit }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return errorResult(unauth);
    const sb = sbForUser(ctx);
    const day = date ?? bogotaToday();
    const { data, error } = await sb.from("work_item_publicaciones").select("id, work_item_id, fecha_fijacion, fecha_desfijacion, tipo_publicacion, title, annotation, despacho, source").eq("fecha_fijacion", day).or("is_archived.is.null,is_archived.eq.false").order("despacho", { ascending: true }).limit(limit ?? 100);
    if (error) return errorResult(error.message);
    const ids = [...new Set((data ?? []).map((r) => r.work_item_id))];
    const { data: items } = ids.length ? await sb.from("work_items").select("id, radicado, title, workflow_type").in("id", ids).is("deleted_at", null) : { data: [] };
    const byId = new Map(
      (items ?? []).map((i) => [i.id, i])
    );
    const rows = (data ?? []).map((r) => ({ ...r, work_item: byId.get(r.work_item_id) ?? null }));
    return textResult(`${rows.length} estados fijados el ${day} (America/Bogota).`, { date: day, estados: rows });
  }
});

// src/lib/mcp/tools/get-actuaciones-hoy.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z7 } from "npm:zod@^3.25.76";
var WINDOW_DAYS = { today: 1, "3days": 3, week: 7 };
var get_actuaciones_hoy_default = defineTool8({
  name: "get_actuaciones_hoy",
  title: "Actuaciones recientes de la cartera",
  description: "Lists actuaciones registered across the whole portfolio within a recent window (today, last 3 days, or last week), based on act_date in America/Bogota.",
  inputSchema: {
    date: z7.string().optional().describe("D\xEDa final YYYY-MM-DD en America/Bogota. Default: hoy."),
    window: z7.enum(["today", "3days", "week"]).optional().describe("Ventana hacia atr\xE1s. Default: today."),
    limit: z7.number().int().min(1).max(200).optional().describe("M\xE1ximo de filas (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date, window, limit }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return errorResult(unauth);
    const sb = sbForUser(ctx);
    const end = date ?? bogotaToday();
    const days = WINDOW_DAYS[window ?? "today"];
    const start = /* @__PURE__ */ new Date(`${end}T00:00:00Z`);
    start.setUTCDate(start.getUTCDate() - (days - 1));
    const from = start.toISOString().slice(0, 10);
    const { data, error } = await sb.from("work_item_acts").select("id, work_item_id, act_date, act_type, description, despacho, source, detected_at").gte("act_date", from).lte("act_date", end).or("is_archived.is.null,is_archived.eq.false").order("act_date", { ascending: false }).limit(limit ?? 100);
    if (error) return errorResult(error.message);
    const ids = [...new Set((data ?? []).map((r) => r.work_item_id))];
    const { data: items } = ids.length ? await sb.from("work_items").select("id, radicado, title, workflow_type").in("id", ids).is("deleted_at", null) : { data: [] };
    const byId = new Map(
      (items ?? []).map((i) => [i.id, i])
    );
    const rows = (data ?? []).map((r) => ({ ...r, work_item: byId.get(r.work_item_id) ?? null }));
    return textResult(`${rows.length} actuaciones entre ${from} y ${end} (America/Bogota).`, {
      date_from: from,
      date_to: end,
      actuaciones: rows
    });
  }
});

// src/lib/mcp/tools/list-deadlines.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z8 } from "npm:zod@^3.25.76";
var list_deadlines_default = defineTool9({
  name: "list_deadlines",
  title: "T\xE9rminos procesales",
  description: "Lists procedural deadlines (t\xE9rminos). By default only genuinely active deadlines are returned; deadlines flagged PENDING_REVIEW are historical/backfilled and are NOT active \u2014 request them explicitly and never present them as live obligations.",
  inputSchema: {
    status: z8.enum(["pending", "pending_review", "all"]).optional().describe("Default: pending (solo activos)."),
    radicado: z8.string().trim().optional().describe("Limitar a un asunto por radicado."),
    limit: z8.number().int().min(1).max(200).optional().describe("M\xE1ximo de filas (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, radicado, limit }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return errorResult(unauth);
    const sb = sbForUser(ctx);
    let workItem = null;
    if (radicado) {
      const resolved = await resolveWorkItem(sb, { radicado });
      if (resolved.error || !resolved.item) return errorResult(resolved.error ?? "Asunto no encontrado.");
      workItem = resolved.item;
    }
    let q = sb.from("work_item_deadlines").select("id, work_item_id, deadline_type, label, description, trigger_event, trigger_date, deadline_date, business_days_count, status").order("deadline_date", { ascending: true }).limit(limit ?? 50);
    const mode = status ?? "pending";
    if (mode === "pending") q = q.eq("status", "PENDING");
    else if (mode === "pending_review") q = q.eq("status", "PENDING_REVIEW");
    if (workItem) q = q.eq("work_item_id", workItem.id);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    const rows = data ?? [];
    const today = bogotaToday();
    const ids = [...new Set(rows.map((r) => r.work_item_id))];
    const { data: items } = ids.length ? await sb.from("work_items").select("id, radicado, title, workflow_type, authority_name, demandantes, demandados").in("id", ids) : { data: [] };
    const byId = new Map(
      (items ?? []).map(
        (i) => [i.id, i]
      )
    );
    const dates = rows.map((r) => String(r.deadline_date ?? "")).filter(Boolean).sort();
    const horizonEnd = dates[dates.length - 1] ?? today;
    const { data: holidayRows } = await sb.from("colombian_holidays").select("holiday_date").gte("holiday_date", dates[0] && dates[0] < today ? dates[0] : today).lte("holiday_date", horizonEnd > today ? horizonEnd : today);
    const holidays = new Set((holidayRows ?? []).map((h) => String(h.holiday_date)));
    const deadlines = rows.map((r) => {
      const row = r;
      const wi = byId.get(String(row.work_item_id)) ?? null;
      const titulo = workItemTitle(wi, String(row.work_item_id));
      const dd = row.deadline_date ? String(row.deadline_date).slice(0, 10) : null;
      const restantes = dd ? businessDaysBetween(today, dd, holidays) : null;
      const urgencia = restantes == null ? "SIN_FECHA" : restantes < 0 ? "VENCIDO" : restantes === 0 ? "VENCE_HOY" : restantes <= 2 ? "CRITICO" : restantes <= 5 ? "PROXIMO" : "NORMAL";
      return {
        ...row,
        radicado: wi?.radicado ?? null,
        titulo,
        workflow_type: wi?.workflow_type ?? null,
        despacho: wi?.authority_name ?? null,
        vencimiento: dd,
        dias_habiles_restantes: restantes,
        urgencia
      };
    });
    const note = mode === "pending" ? "Solo t\xE9rminos activos." : mode === "pending_review" ? "T\xE9rminos en revisi\xF3n (vencidos en el backfill): NO son obligaciones vigentes." : "Incluye activos y en revisi\xF3n; los PENDING_REVIEW no son obligaciones vigentes.";
    return textResult(`${deadlines.length} t\xE9rminos. ${note} (hoy = ${today}, America/Bogota)`, {
      status: mode,
      hoy: today,
      work_item: workItem,
      deadlines
    });
  }
});

// src/lib/mcp/tools/list-clients.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z9 } from "npm:zod@^3.25.76";
var list_clients_default = defineTool10({
  name: "list_clients",
  title: "Listar clientes",
  description: "Lists the signed-in lawyer's clients with the number of active matters linked to each one.",
  inputSchema: {
    search: z9.string().trim().optional().describe("B\xFAsqueda por nombre o identificaci\xF3n."),
    limit: z9.number().int().min(1).max(200).optional().describe("M\xE1ximo de filas (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return errorResult(unauth);
    const sb = sbForUser(ctx);
    let q = sb.from("clients").select("id, name, id_number, email, city, created_at").is("deleted_at", null).order("name", { ascending: true }).limit(limit ?? 50);
    if (search) q = q.or(`name.ilike.%${search}%,id_number.ilike.%${search}%`);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    const ids = (data ?? []).map((c) => c.id);
    const { data: items } = ids.length ? await sb.from("work_items").select("id, client_id").in("client_id", ids).is("deleted_at", null) : { data: [] };
    const counts = {};
    for (const it of items ?? []) {
      const cid = it.client_id;
      if (cid) counts[cid] = (counts[cid] ?? 0) + 1;
    }
    const rows = (data ?? []).map((c) => ({ ...c, active_work_items: counts[c.id] ?? 0 }));
    return textResult(`${rows.length} clientes.`, { clients: rows });
  }
});

// src/lib/mcp/tools/get-client.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z10 } from "npm:zod@^3.25.76";
var get_client_default = defineTool11({
  name: "get_client",
  title: "Detalle de cliente",
  description: "Fetches one client and the matters linked to them. Identify the client by id or by exact/partial name.",
  inputSchema: {
    client_id: z10.string().uuid().optional().describe("UUID del cliente."),
    name: z10.string().trim().optional().describe("Nombre del cliente (coincidencia parcial).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ client_id, name }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return errorResult(unauth);
    if (!client_id && !name) return errorResult("Indica client_id o name.");
    const sb = sbForUser(ctx);
    let q = sb.from("clients").select("id, name, id_number, email, city, address, notes, created_at").is("deleted_at", null).limit(1);
    if (client_id) q = q.eq("id", client_id);
    else if (name) q = q.ilike("name", `%${name}%`);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    const client = data?.[0];
    if (!client) return errorResult("Cliente no encontrado (o no pertenece a tu cuenta).");
    const { data: items } = await sb.from("work_items").select("id, radicado, title, workflow_type, stage, authority_name").eq("client_id", client.id).is("deleted_at", null).limit(200);
    return textResult(
      `${client.name} \u2014 ${items?.length ?? 0} asuntos activos.`,
      { client, work_items: items ?? [] }
    );
  }
});

// src/lib/mcp/tools/add-note.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z11 } from "npm:zod@^3.25.76";
var add_note_default = defineTool12({
  name: "add_note",
  title: "Agregar nota a un asunto",
  description: "Appends a timestamped note to a matter's notes field. This is the only write operation exposed over MCP: it never deletes, reclassifies, or changes the lifecycle of a matter.",
  inputSchema: {
    radicado: z11.string().trim().optional().describe("Radicado del asunto."),
    id: z11.string().uuid().optional().describe("UUID del asunto."),
    content: z11.string().trim().min(1).max(4e3).describe("Texto de la nota.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ radicado, id, content }, ctx) => {
    const denied = requireWriteScope(ctx);
    if (denied) return errorResult(denied);
    const sb = sbForUser(ctx);
    const { item, error } = await resolveWorkItem(sb, { id, radicado }, "id, radicado, notes");
    if (error || !item) return errorResult(error ?? "Asunto no encontrado.");
    const stamp = (/* @__PURE__ */ new Date()).toLocaleString("es-CO", { timeZone: "America/Bogota" });
    const entry = `[${stamp} \xB7 v\xEDa asistente IA] ${content}`;
    const previous = (item.notes ?? "").trim();
    const nextNotes = previous ? `${previous}

${entry}` : entry;
    const { error: upErr } = await sb.from("work_items").update({ notes: nextNotes, updated_at: (/* @__PURE__ */ new Date()).toISOString() }).eq("id", item.id);
    if (upErr) return errorResult(upErr.message);
    return textResult(`Nota agregada al asunto ${item.radicado ?? item.id}.`, {
      work_item_id: item.id,
      note: entry
    });
  }
});

// src/lib/mcp/tools/search.ts
import { defineTool as defineTool13 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z12 } from "npm:zod@^3.25.76";
var search_default = defineTool13({
  name: "search",
  title: "B\xFAsqueda libre",
  description: "Free-text search across the caller's matters: radicado, t\xEDtulo, partes (demandantes/demandados), authority (despacho) and city. Use it for natural queries like 'el caso contra Bancolombia en Medell\xEDn'. Results are RLS-scoped to the caller.",
  inputSchema: {
    query: z12.string().trim().min(2).describe("Texto libre: parte, despacho, ciudad, radicado o t\xEDtulo."),
    workflow_type: z12.string().trim().optional().describe("Filtro opcional: CGP, CPACA, LABORAL, PENAL, TUTELA, PETICION."),
    client_id: z12.string().uuid().optional().describe("Filtro opcional por cliente (UUID)."),
    status: z12.string().trim().optional().describe("Filtro opcional por estado del asunto (p. ej. ACTIVE)."),
    city: z12.string().trim().optional().describe("Filtro opcional por ciudad del despacho."),
    limit: z12.number().int().min(1).max(50).optional().describe("M\xE1ximo de resultados (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, workflow_type, client_id, status, city, limit }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return errorResult(unauth);
    const sb = sbForUser(ctx);
    const terms = query.split(/\s+/).filter((t) => t.length >= 3).slice(0, 4);
    const needles = terms.length ? terms : [query];
    let q = sb.from("work_items").select(
      "id, radicado, title, workflow_type, stage, status, authority_name, authority_city, demandantes, demandados, last_action_date, last_action_description, updated_at"
    ).is("deleted_at", null).order("updated_at", { ascending: false }).limit(limit ?? 20);
    for (const term of needles) {
      const s = `%${term}%`;
      q = q.or(
        [
          `radicado.ilike.${s}`,
          `title.ilike.${s}`,
          `authority_name.ilike.${s}`,
          `authority_city.ilike.${s}`,
          `demandantes.ilike.${s}`,
          `demandados.ilike.${s}`
        ].join(",")
      );
    }
    if (workflow_type) q = q.eq("workflow_type", workflow_type.toUpperCase());
    if (client_id) q = q.eq("client_id", client_id);
    if (status) q = q.eq("status", status.toUpperCase());
    if (city) q = q.ilike("authority_city", `%${city}%`);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    const scored = (data ?? []).map((row) => {
      const r = row;
      const hay = ["radicado", "title", "authority_name", "authority_city", "demandantes", "demandados"].map((k) => String(r[k] ?? "").toLowerCase());
      let score = 0;
      for (const term of needles) {
        const t = term.toLowerCase();
        if (hay[0].includes(t)) score += 2;
        if (hay.slice(1).some((h) => h.includes(t))) score += 1;
      }
      return { ...r, relevance_score: score };
    }).sort((a, b) => b.relevance_score - a.relevance_score);
    return textResult(
      `${scored.length} asuntos coinciden con "${query}".`,
      {
        query,
        filters: { workflow_type: workflow_type ?? null, client_id: client_id ?? null, status: status ?? null, city: city ?? null },
        items: scored
      }
    );
  }
});

// src/lib/mcp/tools/list-alerts.ts
import { defineTool as defineTool14 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z13 } from "npm:zod@^3.25.76";
var list_alerts_default = defineTool14({
  name: "list_alerts",
  title: "Alertas del abogado",
  description: "Lists the caller's judicial alerts (alert_instances). Default: unresolved alerts (PENDING and ACKNOWLEDGED), newest first. Use it to answer 'how many unread alerts do I have'.",
  inputSchema: {
    work_item_id: z13.string().uuid().optional().describe("Limitar a un asunto (UUID)."),
    radicado: z13.string().trim().optional().describe("Limitar a un asunto por radicado."),
    status: z13.string().trim().optional().describe("pending | acknowledged | resolved | all. Default: pendientes + reconocidas."),
    limit: z13.number().int().min(1).max(100).optional().describe("M\xE1ximo de filas (default 30).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ work_item_id, radicado, status, limit }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return errorResult(unauth);
    const sb = sbForUser(ctx);
    let entityId = work_item_id ?? null;
    if (!entityId && radicado) {
      const resolved = await resolveWorkItem(sb, { radicado });
      if (resolved.error || !resolved.item) return errorResult(resolved.error ?? "Asunto no encontrado.");
      entityId = resolved.item.id;
    }
    let q = sb.from("alert_instances").select("id, alert_type, severity, status, title, message, entity_type, entity_id, fired_at, acknowledged_at, read_at").order("fired_at", { ascending: false }).limit(limit ?? 30);
    const normalized = status?.toUpperCase();
    if (!normalized) q = q.in("status", ["PENDING", "ACKNOWLEDGED"]);
    else if (normalized !== "ALL") q = q.eq("status", normalized);
    if (entityId) q = q.eq("entity_id", entityId);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    const rows = data ?? [];
    const wiIds = [
      ...new Set(
        rows.filter((a) => String(a.entity_type ?? "").toUpperCase() === "WORK_ITEM").map((a) => String(a.entity_id ?? "")).filter(Boolean)
      )
    ];
    const { data: items } = wiIds.length ? await sb.from("work_items").select("id, radicado, title, workflow_type").in("id", wiIds) : { data: [] };
    const byId = new Map(
      (items ?? []).map(
        (i) => [i.id, i]
      )
    );
    const alerts = rows.map((a) => {
      const row = a;
      const wi = byId.get(String(row.entity_id ?? "")) ?? null;
      return {
        ...row,
        radicado: wi?.radicado ?? null,
        titulo_asunto: wi?.title ?? null,
        workflow_type: wi?.workflow_type ?? null,
        leida: Boolean(row.read_at)
      };
    });
    const unread = alerts.filter((a) => !a.leida).length;
    return textResult(`${alerts.length} alertas (${unread} sin leer).`, {
      status: status ?? "PENDING+ACKNOWLEDGED",
      work_item_id: entityId,
      unread,
      alerts
    });
  }
});

// src/lib/mcp/tools/list-hearings.ts
import { defineTool as defineTool15 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z14 } from "npm:zod@^3.25.76";
var list_hearings_default = defineTool15({
  name: "list_hearings",
  title: "Audiencias programadas",
  description: "Lists scheduled hearings (audiencias) from the canonical work_item_hearings table, RLS-scoped to the caller. Optionally filter by matter and by date range (ISO dates, America/Bogota calendar).",
  inputSchema: {
    work_item_id: z14.string().uuid().optional().describe("Limitar a un asunto (UUID)."),
    radicado: z14.string().trim().optional().describe("Limitar a un asunto por radicado."),
    date_from: z14.string().trim().optional().describe("Fecha inicial ISO (YYYY-MM-DD)."),
    date_to: z14.string().trim().optional().describe("Fecha final ISO (YYYY-MM-DD)."),
    limit: z14.number().int().min(1).max(100).optional().describe("M\xE1ximo de filas (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ work_item_id, radicado, date_from, date_to, limit }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return errorResult(unauth);
    const sb = sbForUser(ctx);
    let itemId = work_item_id ?? null;
    if (!itemId && radicado) {
      const resolved = await resolveWorkItem(sb, { radicado });
      if (resolved.error || !resolved.item) return errorResult(resolved.error ?? "Asunto no encontrado.");
      itemId = resolved.item.id;
    }
    let q = sb.from("work_item_hearings").select("id, work_item_id, custom_name, status, scheduled_at, occurred_at, duration_minutes, modality, location, meeting_link, decisions_summary").order("scheduled_at", { ascending: true }).limit(limit ?? 50);
    if (itemId) q = q.eq("work_item_id", itemId);
    if (date_from) q = q.gte("scheduled_at", `${date_from}T00:00:00-05:00`);
    if (date_to) q = q.lte("scheduled_at", `${date_to}T23:59:59-05:00`);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    const rows = data ?? [];
    const ids = [...new Set(rows.map((r) => String(r.work_item_id)))];
    const { data: items } = ids.length ? await sb.from("work_items").select("id, radicado, title, workflow_type, authority_name").in("id", ids) : { data: [] };
    const byId = new Map(
      (items ?? []).map(
        (i) => [i.id, i]
      )
    );
    const hearings = rows.map((r) => {
      const row = r;
      const wi = byId.get(String(row.work_item_id)) ?? null;
      return {
        ...row,
        radicado: wi?.radicado ?? null,
        titulo_asunto: wi?.title ?? null,
        workflow_type: wi?.workflow_type ?? null,
        despacho: wi?.authority_name ?? null
      };
    });
    const cap = limit ?? 50;
    const hayMas = hearings.length === cap;
    return textResult(
      `${hearings.length} audiencias${hayMas ? ` (tope de ${cap} alcanzado \u2014 puede haber m\xE1s; sube \`limit\` o acota con date_from/date_to)` : ""}.`,
      {
        work_item_id: itemId,
        range: { from: date_from ?? null, to: date_to ?? null },
        limit: cap,
        hay_mas: hayMas,
        hearings
      }
    );
  }
});

// src/lib/mcp/tools/list-tasks.ts
import { defineTool as defineTool16 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z15 } from "npm:zod@^3.25.76";
var list_tasks_default = defineTool16({
  name: "list_tasks",
  title: "Tareas de expedientes",
  description: "Lists the caller's tasks (work_item_tasks), optionally filtered by matter and status. Default: open tasks ordered by due date.",
  inputSchema: {
    work_item_id: z15.string().uuid().optional().describe("Limitar a un asunto (UUID)."),
    radicado: z15.string().trim().optional().describe("Limitar a un asunto por radicado."),
    status: z15.string().trim().optional().describe("Estado exacto (p. ej. PENDING, IN_PROGRESS, COMPLETED) o 'all'."),
    limit: z15.number().int().min(1).max(100).optional().describe("M\xE1ximo de filas (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ work_item_id, radicado, status, limit }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return errorResult(unauth);
    const sb = sbForUser(ctx);
    let itemId = work_item_id ?? null;
    if (!itemId && radicado) {
      const resolved = await resolveWorkItem(sb, { radicado });
      if (resolved.error || !resolved.item) return errorResult(resolved.error ?? "Asunto no encontrado.");
      itemId = resolved.item.id;
    }
    let q = sb.from("work_item_tasks").select("id, work_item_id, title, description, status, priority, due_date, completed_at, created_at").order("due_date", { ascending: true, nullsFirst: false }).limit(limit ?? 50);
    if (itemId) q = q.eq("work_item_id", itemId);
    if (!status) q = q.neq("status", "COMPLETED");
    else if (status.toLowerCase() !== "all") q = q.eq("status", status.toUpperCase());
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return textResult(`${data?.length ?? 0} tareas.`, {
      work_item_id: itemId,
      status: status ?? "abiertas",
      tasks: data ?? []
    });
  }
});

// src/lib/mcp/tools/get-document-url.ts
import { defineTool as defineTool17 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z16 } from "npm:zod@^3.25.76";
var get_document_url_default = defineTool17({
  name: "get_document_url",
  title: "Enlace del documento de una publicaci\xF3n",
  description: "Returns a short-lived download URL for the PDF attached to a publicaci\xF3n (estado electr\xF3nico) of one of the caller's matters. It never generates new documents; it only exposes an existing attachment under the established access policy.",
  inputSchema: {
    work_item_id: z16.string().uuid().optional().describe("UUID del asunto."),
    radicado: z16.string().trim().optional().describe("Radicado del asunto."),
    document_id: z16.string().uuid().describe("UUID de la publicaci\xF3n (estado) cuyo PDF se solicita.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: false },
  handler: async ({ work_item_id, radicado, document_id }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return errorResult(unauth);
    const sb = sbForUser(ctx);
    const resolved = await resolveWorkItem(sb, { id: work_item_id, radicado });
    if (resolved.error || !resolved.item) return errorResult(resolved.error ?? "Asunto no encontrado.");
    const itemId = resolved.item.id;
    const { data: pub, error } = await sb.from("work_item_publicaciones").select("id, work_item_id, title, tipo_publicacion, fecha_fijacion, pdf_url, pdf_available").eq("id", document_id).maybeSingle();
    if (error) return errorResult(error.message);
    if (!pub) return errorResult("Documento no encontrado (o no pertenece a tu cuenta).");
    if (pub.work_item_id !== itemId) {
      return errorResult("El documento no pertenece al asunto indicado.");
    }
    const publicUrl = pub.pdf_url ?? null;
    if (publicUrl && /^https?:\/\//i.test(publicUrl) && /storage\.googleapis\.com/i.test(publicUrl)) {
      return textResult(`Enlace p\xFAblico del documento de ${pub.title ?? "la publicaci\xF3n"}.`, {
        document_id,
        work_item_id: itemId,
        url: publicUrl,
        source: "public"
      });
    }
    const base = process.env.SUPABASE_URL;
    const res = await fetch(`${base}/functions/v1/get-estado-attachment-url`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${ctx.getToken()}`,
        apikey: process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
      },
      body: JSON.stringify({ publicacion_id: document_id })
    });
    const payload = await res.json().catch(() => ({}));
    if (!res.ok || !payload.url) {
      return errorResult(
        payload.error === "no_pdf_available" ? "Esta publicaci\xF3n no tiene PDF disponible." : `No se pudo obtener el documento: ${payload.error ?? res.status}`
      );
    }
    return textResult("Enlace temporal generado (v\xE1lido ~10 minutos).", {
      document_id,
      work_item_id: itemId,
      url: payload.url,
      source: "signed",
      expires_in_seconds: 600
    });
  }
});

// src/lib/mcp/tools/add-hearing.ts
import { defineTool as defineTool18 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z17 } from "npm:zod@^3.25.76";
var add_hearing_default = defineTool18({
  name: "add_hearing",
  title: "Agendar audiencia",
  description: "Schedules a hearing (audiencia) on one of the caller's matters. Requires the read_write scope. It only inserts new hearings: it never deletes, reschedules by deletion, reclassifies, or changes the lifecycle of a matter.",
  inputSchema: {
    work_item_id: z17.string().uuid().optional().describe("UUID del asunto."),
    radicado: z17.string().trim().optional().describe("Radicado del asunto."),
    date: z17.string().trim().describe("Fecha y hora ISO 8601, p. ej. 2026-08-14T09:00:00-05:00 (hora de Bogot\xE1)."),
    description: z17.string().trim().min(1).max(500).describe("Nombre o descripci\xF3n de la audiencia."),
    location: z17.string().trim().max(300).optional().describe("Lugar o enlace de la audiencia.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ work_item_id, radicado, date, description, location }, ctx) => {
    const denied = requireWriteScope(ctx);
    if (denied) return errorResult(denied);
    const sb = sbForUser(ctx);
    const when = new Date(date);
    if (Number.isNaN(when.getTime())) return errorResult("Fecha inv\xE1lida: usa formato ISO 8601.");
    const resolved = await resolveWorkItem(sb, { id: work_item_id, radicado });
    if (resolved.error || !resolved.item) return errorResult(resolved.error ?? "Asunto no encontrado.");
    const itemId = resolved.item.id;
    const orgId = await callerOrganizationId(sb, ctx.getUserId());
    const { data, error } = await sb.from("work_item_hearings").insert({
      work_item_id: itemId,
      organization_id: orgId,
      custom_name: description,
      scheduled_at: when.toISOString(),
      location: location ?? null,
      status: "SCHEDULED",
      modality: location && /^https?:\/\//i.test(location) ? "VIRTUAL" : "PRESENCIAL",
      created_by: ctx.getUserId(),
      notes_plain_text: "Agendada v\xEDa asistente de IA (MCP)."
    }).select("id, work_item_id, custom_name, scheduled_at, location, status").maybeSingle();
    if (error) return errorResult(error.message);
    return textResult(
      `Audiencia agendada para el asunto ${resolved.item.radicado ?? itemId}.`,
      { hearing: data ?? null }
    );
  }
});

// src/lib/mcp/tools/list-email-links.ts
import { defineTool as defineTool19 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z18 } from "npm:zod@^3.25.76";
var list_email_links_default = defineTool19({
  name: "list_email_links",
  title: "Correos vinculados al expediente",
  description: "Lists the email metadata linked to one matter (work_item_email_links): subject, direction, sender, date, evidence type, how it was matched, confidence, attachments and the Outlook web link. Read-only; Andromeda never stores email bodies.",
  inputSchema: {
    work_item_id: z18.string().uuid().optional().describe("UUID del asunto."),
    radicado: z18.string().trim().optional().describe("Radicado del asunto (alternativa al UUID)."),
    status: z18.enum(["CONFIRMED", "SUGGESTED", "DISMISSED", "ALL"]).optional().describe("Estado del v\xEDnculo. Default: CONFIRMED + SUGGESTED."),
    limit: z18.number().int().min(1).max(100).optional().describe("M\xE1ximo de filas (default 30).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ work_item_id, radicado, status, limit }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return errorResult(unauth);
    const sb = sbForUser(ctx);
    const resolved = await resolveWorkItem(sb, { id: work_item_id, radicado });
    if (resolved.error || !resolved.item) return errorResult(resolved.error ?? "Asunto no encontrado.");
    const item = resolved.item;
    let q = sb.from("work_item_email_links").select(
      "id, subject, direction, sender, recipients, received_at, evidence_type, matched_by, matched_value, confidence, has_attachments, web_link, link_status"
    ).eq("work_item_id", item.id).order("received_at", { ascending: false }).limit(limit ?? 30);
    if (!status) q = q.in("link_status", ["CONFIRMED", "SUGGESTED"]);
    else if (status !== "ALL") q = q.eq("link_status", status);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    const links = data ?? [];
    const titulo = workItemTitle(item);
    return textResult(
      `${links.length} correo(s) vinculado(s) a ${titulo} (${item.radicado ?? "sin radicado"}).`,
      {
        work_item: { id: item.id, radicado: item.radicado ?? null, titulo },
        total: links.length,
        links,
        nota: "Solo metadatos. Andromeda nunca almacena el cuerpo de los correos."
      }
    );
  }
});

// src/lib/mcp/tools/list-detected-processes.ts
import { defineTool as defineTool20 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z19 } from "npm:zod@^3.25.76";
var list_detected_processes_default = defineTool20({
  name: "list_detected_processes",
  title: "Procesos detectados en el correo",
  description: "Lists judicial case numbers (radicados) found in the caller's mailbox that do NOT exist in their Andromeda portfolio yet (detected_processes queue). Use it to help the lawyer triage which ones deserve a matter. Read-only: creating the matter always happens in the app.",
  inputSchema: {
    status: z19.enum(["PENDING", "DISMISSED", "CREATED", "ALL"]).optional().describe("Estado de la detecci\xF3n. Default: PENDING."),
    limit: z19.number().int().min(1).max(200).optional().describe("M\xE1ximo de filas (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return errorResult(unauth);
    const sb = sbForUser(ctx);
    let q = sb.from("detected_processes").select(
      "id, radicado, subject, sender, web_link, partes_inferidas, despacho_inferido, workflow_inferido, ciudad_inferida, first_seen_at, last_seen_at, occurrences, status"
    ).order("last_seen_at", { ascending: false }).limit(limit ?? 50);
    const wanted = status ?? "PENDING";
    if (wanted !== "ALL") q = q.eq("status", wanted);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    const rows = data ?? [];
    return textResult(
      `${rows.length} proceso(s) detectado(s) en el correo con estado ${wanted}.`,
      {
        total: rows.length,
        status: wanted,
        procesos: rows,
        nota: "Andromeda nunca crea expedientes autom\xE1ticamente: el abogado decide en la app."
      }
    );
  }
});

// src/lib/mcp/tools/atenia-health-overview.ts
import { defineTool as defineTool21 } from "npm:@lovable.dev/mcp-js@0.20.0";
var atenia_health_overview_default = defineTool21({
  name: "atenia_health_overview",
  title: "Atenia \xB7 Salud de la plataforma (solo administradores)",
  description: "PLATFORM ADMINS ONLY. Returns the current Andromeda platform health snapshot: latest Atenia preflight verdict, service heartbeats and the last cron runs. Non-admin callers get a clean refusal.",
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  inputSchema: {},
  handler: async (_args, ctx) => {
    const { error: denied, sb } = await requirePlatformAdmin(ctx);
    if (denied) return errorResult(denied);
    const [preflight, heartbeats, crons] = await Promise.all([
      sb.from("atenia_preflight_checks").select("id, trigger, started_at, finished_at, duration_ms, overall_status, decision, providers_tested, providers_passed, providers_failed").order("started_at", { ascending: false }).limit(1),
      sb.from("system_health_heartbeat").select("service, last_status, last_ok_at, last_error_at, last_message, updated_at").order("service"),
      sb.from("atenia_cron_runs").select("job_name, status, started_at, finished_at").order("started_at", { ascending: false }).limit(25)
    ]);
    const hb = heartbeats.data ?? [];
    const cronRows = crons.data ?? [];
    const degraded = hb.filter((h) => h.last_status !== "OK");
    const failedCrons = cronRows.filter((c) => c.status === "FAILED");
    return textResult(
      `Salud de la plataforma: ${degraded.length} servicio(s) degradado(s), ${failedCrons.length} cron(s) fallido(s) en las \xFAltimas ejecuciones.`,
      {
        ultimo_preflight: (preflight.data ?? [])[0] ?? null,
        heartbeats: hb,
        servicios_degradados: degraded,
        crons_recientes: cronRows,
        crons_fallidos: failedCrons
      }
    );
  }
});

// src/lib/mcp/tools/atenia-provider-status.ts
import { defineTool as defineTool22 } from "npm:@lovable.dev/mcp-js@0.20.0";
var atenia_provider_status_default = defineTool22({
  name: "atenia_provider_status",
  title: "Atenia \xB7 Estado de proveedores judiciales (solo administradores)",
  description: "PLATFORM ADMINS ONLY. Per-provider status from the latest Atenia preflight run (CPNU, SAMAI, Publicaciones Procesales, SAMAI Estados), including consecutive failures. Non-admin callers get a clean refusal.",
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  inputSchema: {},
  handler: async (_args, ctx) => {
    const { error: denied, sb } = await requirePlatformAdmin(ctx);
    if (denied) return errorResult(denied);
    const { data, error } = await sb.from("atenia_preflight_checks").select("id, trigger, started_at, overall_status, decision, results, consecutive_failures_by_provider, providers_tested, providers_passed, providers_failed").order("started_at", { ascending: false }).limit(1);
    if (error) return errorResult(error.message);
    const run = (data ?? [])[0];
    if (!run) return textResult("No hay ejecuciones de preflight registradas.", { proveedores: [] });
    const results = Array.isArray(run.results) ? run.results : [];
    const failing = results.filter((r) => String(r.status ?? "").toUpperCase() !== "OK");
    return textResult(
      `Preflight ${String(run.overall_status)}: ${run.providers_passed}/${run.providers_tested} proveedores OK, ${failing.length} con fallo.`,
      {
        ejecutado_en: run.started_at,
        overall_status: run.overall_status,
        decision: run.decision ?? null,
        proveedores: results,
        proveedores_con_fallo: failing,
        fallos_consecutivos: run.consecutive_failures_by_provider ?? {}
      }
    );
  }
});

// src/lib/mcp/tools/atenia-recent-incidents.ts
import { defineTool as defineTool23 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z20 } from "npm:zod@^3.25.76";
var atenia_recent_incidents_default = defineTool23({
  name: "atenia_recent_incidents",
  title: "Atenia \xB7 Incidentes recientes (solo administradores)",
  description: "PLATFORM ADMINS ONLY. Lists WARN/ERROR system health events and failed cron runs in the last N days (default 7). Non-admin callers get a clean refusal.",
  inputSchema: {
    days: z20.number().int().min(1).max(90).optional().describe("Ventana en d\xEDas (default 7)."),
    limit: z20.number().int().min(1).max(200).optional().describe("M\xE1ximo de eventos (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days, limit }, ctx) => {
    const { error: denied, sb } = await requirePlatformAdmin(ctx);
    if (denied) return errorResult(denied);
    const window = days ?? 7;
    const since = new Date(Date.now() - window * 864e5).toISOString();
    const [events, crons] = await Promise.all([
      sb.from("system_health_events").select("id, service, status, message, metadata, created_at, organization_id").in("status", ["WARN", "ERROR"]).gte("created_at", since).order("created_at", { ascending: false }).limit(limit ?? 100),
      sb.from("atenia_cron_runs").select("id, job_name, status, started_at, finished_at, details").eq("status", "FAILED").gte("started_at", since).order("started_at", { ascending: false }).limit(limit ?? 100)
    ]);
    if (events.error) return errorResult(events.error.message);
    const evRows = events.data ?? [];
    const cronRows = crons.data ?? [];
    return textResult(
      `\xDAltimos ${window} d\xEDa(s): ${evRows.length} evento(s) WARN/ERROR y ${cronRows.length} cron(s) fallido(s).`,
      {
        ventana_dias: window,
        desde: since,
        eventos: evRows,
        crons_fallidos: cronRows
      }
    );
  }
});

// src/lib/mcp/index.ts
var projectRef = "qvuukbqcvlnvmcvcruji";
var mcp_default = defineMcp({
  name: "andromeda-mcp",
  title: "Andromeda Legal",
  version: "0.4.0",
  instructions: [
    "Herramientas de Andromeda para abogados litigantes en Colombia. Todo el acceso est\xE1 restringido por RLS al usuario autenticado.",
    "Empieza por `get_user_context` para saber con qui\xE9n hablas y el tama\xF1o de su cartera.",
    "Cartera: `list_work_items`, `get_work_item`, `list_clients`, `get_client`. Para consultas en lenguaje natural ('el caso contra Bancolombia en Medell\xEDn') usa `search`.",
    "Detalle por expediente: `list_actuaciones` (actuaciones) y `list_publicaciones` (estados electr\xF3nicos).",
    "Documentos: `get_document_url` devuelve un enlace temporal al PDF de una publicaci\xF3n; nunca genera documentos nuevos.",
    "Correo: `list_email_links` muestra los correos vinculados a un expediente (solo metadatos, nunca el cuerpo) y `list_detected_processes` la cola de radicados hallados en el buz\xF3n que a\xFAn no existen como expediente.",
    "Agenda diaria: `get_estados_hoy` y `get_actuaciones_hoy`; 'hoy' siempre es el d\xEDa calendario en America/Bogota.",
    "Agenda y pendientes: `list_hearings` (audiencias), `list_tasks` (tareas) y `list_alerts` (alertas sin resolver).",
    "T\xE9rminos: `list_deadlines`. Los t\xE9rminos con estado PENDING_REVIEW provienen de un backfill hist\xF3rico y NO son obligaciones vigentes.",
    "Escritura: solo `add_note` y `add_hearing`, y ambas exigen el permiso `read_write`. Nunca existe eliminaci\xF3n, reclasificaci\xF3n ni cambio de ciclo de vida v\xEDa MCP.",
    "No inventes plazos ni cifras: si una herramienta no devuelve el dato, dilo expl\xEDcitamente.",
    "Las herramientas `atenia_*` son exclusivas de administradores de la plataforma; para cualquier otro usuario devuelven un rechazo limpio. No las ofrezcas si el usuario no es administrador."
  ].join(" "),
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_user_context_default,
    search_default,
    list_work_items_default,
    get_work_item_default,
    list_actuaciones_default,
    list_publicaciones_default,
    list_recent_estados_default,
    get_estados_hoy_default,
    get_actuaciones_hoy_default,
    list_deadlines_default,
    list_alerts_default,
    list_hearings_default,
    list_tasks_default,
    get_document_url_default,
    list_email_links_default,
    list_detected_processes_default,
    list_clients_default,
    get_client_default,
    add_note_default,
    add_hearing_default,
    atenia_health_overview_default,
    atenia_provider_status_default,
    atenia_recent_incidents_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
