-- Create enum type for process phases
CREATE TYPE public.process_phase AS ENUM (
  'PENDIENTE_REGISTRO_MEDIDA_CAUTELAR',
  'PENDIENTE_NOTIFICACION_PERSONAL',
  'PENDIENTE_NOTIFICACION_AVISO_EMPLAZAMIENTO',
  'PENDIENTE_CONTESTAR_EXCEPCIONES_PREVIAS',
  'PENDIENTE_PRONUNCIARSE_EXCEPCIONES',
  'PENDIENTE_AUDIENCIA_INICIAL',
  'PENDIENTE_AUDIENCIA_INSTRUCCION',
  'PENDIENTE_ALEGATOS_SENTENCIA',
  'PENDIENTE_SUSTENTAR_APELACION'
);

-- Add phase column to monitored_processes
ALTER TABLE public.monitored_processes 
ADD COLUMN phase public.process_phase DEFAULT 'PENDIENTE_REGISTRO_MEDIDA_CAUTELAR';