
ALTER TABLE public.alert_instances DROP CONSTRAINT IF EXISTS alert_instances_alert_type_check;
ALTER TABLE public.alert_instances
  ADD CONSTRAINT alert_instances_alert_type_check
  CHECK (alert_type IS NULL OR alert_type = ANY (ARRAY[
    'ACTUACION_NUEVA','ACTUACION_MODIFIED','ESTADO_NUEVO','ESTADO_MODIFIED',
    'TERMINO_CRITICO','TERMINO_VENCIDO','BRECHA_COBERTURA_ESTADOS','PUBLICACIONES_NUEVAS',
    'SYNC_AUTH_FAILURE','SYNC_FAILURE','WATCHDOG_ESCALATION','WATCHDOG_INVARIANT',
    'PROVIDER_SECRET_DECRYPT_FAILED','MISSING_PROVIDER_SECRET',
    'LEXY_DAILY','DAILY_WELCOME',
    'PROROGATION_DEADLINE','PETICION_DEADLINE','PETICION_OVERDUE','PETICION_REMINDER',
    'HEARING_CREATED','HEARING_REMINDER','HEARING_TODAY','HEARING_SUSPENDED'
  ]));
