ALTER TABLE public.alert_instances DROP CONSTRAINT IF EXISTS alert_instances_alert_type_check;
ALTER TABLE public.alert_instances ADD CONSTRAINT alert_instances_alert_type_check CHECK (
  alert_type = ANY (ARRAY[
    'TERMINO_CRITICO','TERMINO_POR_VENCER','TERMINO_VENCIDO','ACTUACION_RETROACTIVA','ACTUACION_CRITICA',
    'HEARING_TODAY','HEARING_UPCOMING','MONITOREO_SIN_INGESTA','MONITOREO_SIN_PROVEEDOR','MONITOREO_DESACTIVADO',
    'SUGERENCIA_PENDIENTE','LEXY_DAILY','INGESTA_MASIVA','BRECHA_COBERTURA_ESTADOS','SYNC_AUTH_FAILURE',
    'SYNC_FAILURE','WATCHDOG_ESCALATION','WATCHDOG_INVARIANT','PROVIDER_SECRET_DECRYPT_FAILED',
    'MISSING_PROVIDER_SECRET','DAILY_WELCOME','PROROGATION_DEADLINE','PETICION_DEADLINE','PETICION_OVERDUE',
    'PETICION_REMINDER','HEARING_CREATED','HEARING_REMINDER','HEARING_SUSPENDED','ACTUACION_NUEVA',
    'ACTUACION_MODIFIED','ESTADO_NUEVO','ESTADO_MODIFIED','PUBLICACIONES_NUEVAS','SYSTEM_UNTYPED'
  ])
);