ALTER TABLE public.work_item_deadlines DROP CONSTRAINT IF EXISTS work_item_deadlines_status_check;
ALTER TABLE public.work_item_deadlines ADD CONSTRAINT work_item_deadlines_status_check
  CHECK (status IN (
    'PENDING','PENDING_REVIEW','HISTORICAL_BACKFILL','MET','MISSED','CANCELLED',
    'REQUIERE_REVISION_MANUAL','SUGGESTED_BY_EMAIL','SUGGESTED_BY_PROVIDER',
    'FULFILLED','FULFILLED_BY_EMAIL_EVIDENCE','INVALID_NO_TERM','VENCIDO_SIN_SUBSANAR',
    'DISMISSED','SIN_ANCLA_DISPONIBLE','PRESUNCION_DESCARTADA_POR_AVANCE'
  ));